FROM php:8.1-apache

RUN apt-get update && apt-get install -y imagemagick libmagickwand-dev libpng-dev libjpeg-dev libfreetype6-dev

RUN pecl install imagick

RUN docker-php-ext-enable imagick

RUN docker-php-ext-install pdo_mysql

RUN { \
    echo 'post_max_size = 100M'; \
    echo 'upload_max_filesize = 100M'; \
    echo 'max_execution_time = 600S'; \
    echo 'extension=imagick.so'; \
} > /usr/local/etc/php/conf.d/docker-php-upload.ini;

COPY . /var/www/html/

RUN sed -i 's|DocumentRoot /var/www/html|DocumentRoot /var/www/html/public|' /etc/apache2/sites-available/000-default.conf \
    && echo "<Directory /var/www/html/public>\n    AllowOverride All\n    Require all granted\n</Directory>" >> /etc/apache2/sites-available/000-default.conf

VOLUME /var/www/html
EXPOSE 80
CMD ["apache2-foreground"]
